const productos = [
    { id: '1', nombre: 'iPhone 14 Pro Max 1tb', marca: 'apple', categoria: 'celulares', descripcion: 'El iPhone 14 Pro Max te permite captar detalles increíbles gracias a su cámara gran angular de 48 MP. Además, trae la Dynamic Island y una pantalla siempre activa, para que puedas interactuar con tu iPhone de una forma completamente nueva. Y viene con Detección de Choques, una funcionalidad de seguridad que pide ayuda cuando no estás en condiciones de hacerlo.', precio: '9799900', imagen: 'https://i.postimg.cc/xjPGV2PV/i-Phone14-Pro-Max-4-9dca631e-9f5d-4916-9e13-a92448e30a36-300x-removebg-preview.png', imagen_2: 'https://i.postimg.cc/BvxMc6Wh/i-Phone14-Pro-Max-5-43565463-4c94-4e2f-8033-80b7418ff8e2-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/SNPnVfks/i-Phone14-Pro-Max-1-810bdb67-a0db-42c9-b648-786f217fb1b0-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/d310jLfr/i-Phone14-Pro-Max-3-b3469c00-8d33-4c52-a8b7-510c707f38a6-900x-removebg-preview.png' },
    { id: '2', nombre: 'Play Station 5', marca: 'sony', categoria: 'videojuegos', descripcion: 'Con la PlayStation 5, aproveche toda la potencia del procesador AMD Ryzen Zen 2, una GPU AMD RDNA 2 10.28 TFLOPs, 16 GB GDDR6 y una unidad SSD de 865GB para una experiencia extraordinaria donde la acción se vuelve más rápida, suave y explosiva y donde los movimientos son increíblemente claros. Los juegos brillan con detalles muy realistas como nunca antes se habían visto.', precio: '3599000', imagen: 'https://i.postimg.cc/tg0nVSzz/Play-Station5-1-300x-removebg-preview.png', imagen_2: 'https://i.postimg.cc/Kvf2BWRL/Play-Station5-2-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/HnS6sbkJ/Play-Station5-5-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/tCBgpJdL/Play-Station5-8-900x-removebg-preview.png' },
    { id: '3', nombre: 'Redmi Buds Air 2 Neo', marca: 'xiaomi', categoria: 'accesorios', descripcion: 'La batería de 480 mAh proporciona 20 horas de reproducción con cancelación activa de ruido (ANC) activada. Gracias a la carga rápida, podrás olvidarte de la carga constante y disfrutar de la libertad de escucha.', precio: '269900', imagen: 'https://cdn.shopify.com/s/files/1/0485/4566/1094/products/RealmeBudsAir2Neo-1_300x.png?v=1663799062', imagen_2: 'https://i.postimg.cc/KYBFk8Lc/Realme-Buds-Air2-Neo-2-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/ZYrc7tP9/Realme-Buds-Air2-Neo-3-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/TPLjnZY3/Realme-Buds-Air2-Neo-4-900x-removebg-preview.png' },
    { id: '4', nombre: 'MacBook Air M1 256gb', marca: 'apple', categoria: 'computadores', descripcion: 'MacBook Air, la computadora portátil más delgada y liviana de Apple, es transformada por el poderoso chip Apple M1. Con un aumento de rendimiento espectacular para la CPU y la GPU. Y hasta 18 horas de duración de la batería.', precio: '4449900', imagen: 'https://i.postimg.cc/zGHRvZTB/Macbook-Air-M1-1-300x-removebg-preview.png', imagen_2: 'https://i.postimg.cc/L6Wnjhqj/Macbook-Air-M1-2-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/1RCtZ4rb/Macbook-Air-M1-4-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/DfM2MH2T/Macbook-Air-M1-3-900x-removebg-preview.png' },
    { id: '5', nombre: 'iPad Pro 256gb Wifi 2021', marca: 'apple', categoria: 'tablets', descripcion: 'Superpotenciado con el chip M1 de Apple. La experiencia iPad definitiva. Ahora con el rendimiento increíble del chip M1 yuna pantalla XDR espectacular.', precio: '3899900', imagen: 'https://i.postimg.cc/vmqFkxWm/i-Pad-Pro211-256gb-5-900x-removebg-preview.png', imagen_2: 'https://i.postimg.cc/zvkk2Kgt/i-Pad-Pro211-256gb-4-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/KzDLmF84/i-Pad-Pro211-256gb-1-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/DfCJ6xJV/i-Pad-Pro211-256gb-6-900x-removebg-preview.png' },
    { id: '6', nombre: 'iPhone 14 Pro Max 1tb', marca: 'apple', categoria: 'celulares', descripcion: 'El iPhone 14 Pro Max te permite captar detalles increíbles gracias a su cámara gran angular de 48 MP. Además, trae la Dynamic Island y una pantalla siempre activa, para que puedas interactuar con tu iPhone de una forma completamente nueva. Y viene con Detección de Choques, una funcionalidad de seguridad que pide ayuda cuando no estás en condiciones de hacerlo.', precio: '9799900', imagen: 'https://i.postimg.cc/xjPGV2PV/i-Phone14-Pro-Max-4-9dca631e-9f5d-4916-9e13-a92448e30a36-300x-removebg-preview.png', imagen_2: 'https://i.postimg.cc/BvxMc6Wh/i-Phone14-Pro-Max-5-43565463-4c94-4e2f-8033-80b7418ff8e2-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/SNPnVfks/i-Phone14-Pro-Max-1-810bdb67-a0db-42c9-b648-786f217fb1b0-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/d310jLfr/i-Phone14-Pro-Max-3-b3469c00-8d33-4c52-a8b7-510c707f38a6-900x-removebg-preview.png' },
    { id: '7', nombre: 'Play Station 5', marca: 'sony', categoria: 'videojuegos', descripcion: 'Con la PlayStation 5, aproveche toda la potencia del procesador AMD Ryzen Zen 2, una GPU AMD RDNA 2 10.28 TFLOPs, 16 GB GDDR6 y una unidad SSD de 865GB para una experiencia extraordinaria donde la acción se vuelve más rápida, suave y explosiva y donde los movimientos son increíblemente claros. Los juegos brillan con detalles muy realistas como nunca antes se habían visto.', precio: '3599000', imagen: 'https://i.postimg.cc/tg0nVSzz/Play-Station5-1-300x-removebg-preview.png', imagen_2: 'https://i.postimg.cc/Kvf2BWRL/Play-Station5-2-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/HnS6sbkJ/Play-Station5-5-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/tCBgpJdL/Play-Station5-8-900x-removebg-preview.png' },
    { id: '8', nombre: 'Redmi Buds Air 2 Neo', marca: 'xiaomi', categoria: 'accesorios', descripcion: 'La batería de 480 mAh proporciona 20 horas de reproducción con cancelación activa de ruido (ANC) activada. Gracias a la carga rápida, podrás olvidarte de la carga constante y disfrutar de la libertad de escucha.', precio: '269900', imagen: 'https://cdn.shopify.com/s/files/1/0485/4566/1094/products/RealmeBudsAir2Neo-1_300x.png?v=1663799062', imagen_2: 'https://i.postimg.cc/KYBFk8Lc/Realme-Buds-Air2-Neo-2-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/ZYrc7tP9/Realme-Buds-Air2-Neo-3-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/TPLjnZY3/Realme-Buds-Air2-Neo-4-900x-removebg-preview.png' },
    { id: '9', nombre: 'MacBook Air M1 256gb', marca: 'apple', categoria: 'computadores', descripcion: 'MacBook Air, la computadora portátil más delgada y liviana de Apple, es transformada por el poderoso chip Apple M1. Con un aumento de rendimiento espectacular para la CPU y la GPU. Y hasta 18 horas de duración de la batería.', precio: '4449900', imagen: 'https://i.postimg.cc/zGHRvZTB/Macbook-Air-M1-1-300x-removebg-preview.png', imagen_2: 'https://i.postimg.cc/L6Wnjhqj/Macbook-Air-M1-2-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/1RCtZ4rb/Macbook-Air-M1-4-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/DfM2MH2T/Macbook-Air-M1-3-900x-removebg-preview.png' },
    { id: '10', nombre: 'iPad Pro 256gb Wifi 2021', marca: 'apple', categoria: 'tablets', descripcion: 'Superpotenciado con el chip M1 de Apple. La experiencia iPad definitiva. Ahora con el rendimiento increíble del chip M1 yuna pantalla XDR espectacular.', precio: '3899900', imagen: 'https://i.postimg.cc/vmqFkxWm/i-Pad-Pro211-256gb-5-900x-removebg-preview.png', imagen_2: 'https://i.postimg.cc/zvkk2Kgt/i-Pad-Pro211-256gb-4-900x-removebg-preview.png', imagen_3: 'https://i.postimg.cc/KzDLmF84/i-Pad-Pro211-256gb-1-900x-removebg-preview.png', imagen_4: 'https://i.postimg.cc/DfCJ6xJV/i-Pad-Pro211-256gb-6-900x-removebg-preview.png' },
];

export const gFetch = (id) => {
    return new Promise((resolve, reject) => {
        // acciones 
        // reject('REchazado')
        setTimeout(() => {
            // acciones
            resolve(id ? productos.find(producto => producto.id === id) : productos) // tardar 3 segundos 
            reject(console.log('error'))
        }, 3000)
    })
}